//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFAplikacija.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFAplikacija.lang.MyResources", typeof(MyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOMAĆI.
        /// </summary>
        internal static string lbDomaciTim {
            get {
                return ResourceManager.GetString("lbDomaciTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOSTI.
        /// </summary>
        internal static string lbGostujuciTim {
            get {
                return ResourceManager.GetString("lbGostujuciTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite vaš tim:.
        /// </summary>
        internal static string lblChooseTeams {
            get {
                return ResourceManager.GetString("lblChooseTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj gubitaka.
        /// </summary>
        internal static string lblGamesLost {
            get {
                return ResourceManager.GetString("lblGamesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj odigranih utakmica.
        /// </summary>
        internal static string lblGamesPlayed {
            get {
                return ResourceManager.GetString("lblGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj pobjeda.
        /// </summary>
        internal static string lblGamesWon {
            get {
                return ResourceManager.GetString("lblGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj razlike.
        /// </summary>
        internal static string lblGoalDifference {
            get {
                return ResourceManager.GetString("lblGoalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj primljenih.
        /// </summary>
        internal static string lblGoalsReceived {
            get {
                return ResourceManager.GetString("lblGoalsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj golova.
        /// </summary>
        internal static string lblGoalsScored {
            get {
                return ResourceManager.GetString("lblGoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi.
        /// </summary>
        internal static string lblPlayerGoalsScored {
            get {
                return ResourceManager.GetString("lblPlayerGoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string lblPlayerName {
            get {
                return ResourceManager.GetString("lblPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj.
        /// </summary>
        internal static string lblPlayerNumber {
            get {
                return ResourceManager.GetString("lblPlayerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija.
        /// </summary>
        internal static string lblPlayerPosition {
            get {
                return ResourceManager.GetString("lblPlayerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuti kartoni.
        /// </summary>
        internal static string lblPlayerYellowCards {
            get {
                return ResourceManager.GetString("lblPlayerYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA KOD.
        /// </summary>
        internal static string lblRepresentationCode {
            get {
                return ResourceManager.GetString("lblRepresentationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string lblRepresentationName {
            get {
                return ResourceManager.GetString("lblRepresentationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo odaberite rezoluciju:.
        /// </summary>
        internal static string lblResolution {
            get {
                return ResourceManager.GetString("lblResolution", resourceCulture);
            }
        }
    }
}
